# version: '3.6'
# services:
#   pgDB:
#     image: postgis/postgis:12-2.5-alpine
#     restart: always
#     ports:
#       - '5432:5432'
#     volumes:
#       - db_data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_PASSWORD: password
# volumes:
#   db_data:
version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - .env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data: # named volumes can be managed easier using docker-compose
